let log4js = require('log4js');
let fs = require('fs');
let path = require('path');
let directory = './.reports/json-output-folder';

exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub/',
    framework: 'custom',
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    specs: ['./features/*.feature'],
    capabilities: {
        browserName: 'chrome'
    },

    cucumberOpts: {
        require: ['./stepDefinations/*.js', './hooks/*.js'],
        format: 'json:.reports/results.json',
        strict: true,
        tags: '@customerLogin'
    },

    beforeLaunch: function () {
        if (fs.existsSync('./logs/site.log')) {
            fs.unlinkSync('./logs/site.log')
        }
        if (fs.existsSync(directory)) {
        fs.readdir(directory, (err, files) => {
            if (err) throw err;
          
            for (const file of files) {
              fs.unlink(path.join(directory, file), err => {
                if (err) throw err;
              });
            }
          })};
        log4js.configure({
            appenders: {
                out: { type: 'console' },
                app: { type: 'file', filename: 'logs/site.log' }
            },
            categories: {
                default: { appenders: ['out', 'app'], level: 'debug' }
            }
        });
    },

    onPrepare: function () {
        browser.logger = log4js.getLogger('protractorLog4js');
        browser.manage().window().maximize();
    },

    plugins: [{
        package: 'protractor-multiple-cucumber-html-reporter-plugin',
        options: {
            automaticallyGenerateReport: true,
            removeExistingJsonReportFile: true,
            openReportInBrowser: true,
            pageTitle: "NAGP Protractor Assignment Report",
            pageFooter: "<div><p>test report generated by Nupur Saini(314829)</p></div>",
            customData: {
                title: 'Protractor Assignment Report',
                data: [
                    { label: 'Project', value: 'NAGP' },
                    { label: 'Created By', value: 'Nupur Saini' }
                ]
            }
        },

    }]
}
